name: HyperX Build

on:
  - push
  - pull_request

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
            cmake . -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
            cmake --build .

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build
        run: msbuild HyperX.sln /p:Configuration=Release

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
            cmake . -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
            cmake --build .

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          local-cache: true
      - name: Download and set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          cache-disabled: true
          cache-key: 'custom-cache-key'
          sdk-version: |
            24
            30
            35
          build-tools-version: 35.0.0
          cmake-version: 3.10.2.4988404
          ndk-version: 27.2.12479018
          generate-job-summary: false
      - name: Extra needed SDK
        run: |
          sudo apt install clang build-essential -y
          sudo apt install libc6-dev -y
          sudo apt install g++ -y
          sudo apt install make -y
          sudo apt install libssl-dev -y
          sudo apt install git -y
          sudo apt install cmake -y
          sudo apt install pkg-config -y
          sudo apt install libboost-all-dev -y
          sudo apt install libstdc++6 -y
          sudo apt install libc++-dev -y
          sudo apt install libc++abi-dev -y
      - name: Configure Android SDK and NDK Versions
        run: |
          mkdir -p $HOME/.android
          echo 'sdk.dir=$ANDROID_SDK_ROOT' > $HOME/.android/repositories.cfg
          echo 'ndk.dir=$ANDROID_NDK_ROOT' >> $HOME/.android/repositories.cfg
          sed -i 's/android-30/android-35/' $(grep -rl 'android-30' .)
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 24/' $(grep -rl 'minSdkVersion' .)
          sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 30/' $(grep -rl 'targetSdkVersion' .)
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/r27c
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME
      - name: Build
        run: |
            cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=24 -DCMAKE_BUILD_TYPE=Release
            cmake --build .