name: HyperZ Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
    build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build (Linux)
      run: |
          cmake . -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
          cmake --build .

    build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4

    - name: Build (Windows)
      uses: microsoft/setup-msbuild@v1
      run: msbuild HyperZ.sln /p:Configuration=Release

    build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build (macOS)
      run: |
          cmake . -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
          cmake --build .

    build-android:
    steps:
    - uses: actions/checkout@v4