name: HyperX Build

on:
  - push
  - pull_request

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
            cmake . -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
            cmake --build .

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build
        run: msbuild HyperX.sln /p:Configuration=Release

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
            cmake . -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
            cmake --build .

  build-xbox:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build
        run: msbuild HyperX.sln /p:Configuration=Release /p:Platform=ARM64